name: build
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/*'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: adopt
    - name: Build with Gradle
      run: gradle build
    - name: Capture build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/libs/
